# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidato',
            name='votos_obtenidos',
            field=models.IntegerField(default=0, verbose_name='Cantidad de Votos'),
        ),
    ]
