# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 13:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('votos', '0002_candidato_votos_obtenidos'),
    ]

    operations = [
        migrations.AddField(
            model_name='distrito',
            name='votos_totales',
            field=models.IntegerField(default=0, verbose_name='Gente que fue a votar'),
        ),
    ]
